"""add_withings_auth

Revision ID: c1826b108e86
Revises: b5f902b08422
Create Date: 2026-01-09 20:02:13.926102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1826b108e86'
down_revision = 'b5f902b08422'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withings_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('withings_userid', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_withings_auth_id'), 'withings_auth', ['id'], unique=False)
    op.create_index(op.f('ix_withings_auth_withings_userid'), 'withings_auth', ['withings_userid'], unique=True)
    op.drop_index('ix_sync_logs_user_direction_source', table_name='sync_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sync_logs_user_direction_source', 'sync_logs', ['user_id', 'sync_direction', 'source_activity_id'], unique=False)
    op.drop_index(op.f('ix_withings_auth_withings_userid'), table_name='withings_auth')
    op.drop_index(op.f('ix_withings_auth_id'), table_name='withings_auth')
    op.drop_table('withings_auth')
    # ### end Alembic commands ###
